api:
  customer:
    url: http://localhost:8080/customer

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/customers?createDatabaseIfNotExist=true}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  flyway:
    enabled: true
    default-schema: public

csvFile: src/main/resources/data/customers.csv